global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 15s

scrape_configs:
  - job_name: triage-ml-api
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - api-sklearn:8000
          - api-onnx:8000
        labels:
          service: triage-ml
